//
// Created by 90175 on 2024/11/20.
//

#ifndef STM32F103C8T6PROJECT_SOFTWARE_SPI_H
#define STM32F103C8T6PROJECT_SOFTWARE_SPI_H

void SOFTWARE_SPI_W_CS(uint8_t BitValue);
void SOFTWARE_SPI_INIT();
void SOFTWARE_SPI_W_SCK(uint8_t BitValue);
uint8_t SOFTWARE_SPI_R_MISO();
void SOFTWARE_SPI_W_MOSI(uint8_t BitValue);
void SOFTWARE_SPI_START();
void SOFTWARE_SPI_STOP();
uint8_t SOFTWARE_SPI_SWAPBYTE(uint8_t BYTE);


#endif //STM32F103C8T6PROJECT_SOFTWARE_SPI_H
