//
// Created by 90175 on 2024/11/18.
//

#ifndef STM32F103C8T6PROJECT_SOFTWARE_I2C_H
#define STM32F103C8T6PROJECT_SOFTWARE_I2C_H


void SOFTWARE_I2C_INIT();
void SOFTWARE_I2C_W_SCL(uint8_t bitValue);
void SOFTWARE_I2C_W_SDA(uint8_t bitValue);
uint8_t SOFTWARE_I2C_R_SDA();
void SOFTWARE_I2C_START();
void SOFTWARE_I2C_STOP();
void SOFTWARE_I2C_SEND_BYTE(uint8_t BYTE);
void SOFTWARE_I2C_SEND_ACK(uint8_t BYTE);
uint8_t SOFTWARE_I2C_SEND_RECEIVE_BYTE();
uint8_t SOFTWARE_I2C_SEND_RECEIVE_ACK();

// ==============

void SOFTWARE_I2C_main();


#endif //STM32F103C8T6PROJECT_SOFTWARE_I2C_H
